apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: lounge.yaakov.online
  namespace: thelounge
spec:
  secretName: lounge.yaakov.online
  issuerRef:
    name: letsencrypt-yaakov.online
    kind: ClusterIssuer
  commonName: lounge.yaakov.online
  dnsNames:
    - lounge.yaakov.online
  acme:
    config:
      - dns01:
          provider: azure-dns
        domains:
        - lounge.yaakov.online
