---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: thelounge
  name: thelounge
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: thelounge
    spec:
      containers:
      - name: thelounge
        image: thelounge/thelounge:3.0.0-rc.5
        volumeMounts:
        - mountPath: /home/lounge/data
          name: data
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: thelounge-data
