apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: thelounge
  name: thelounge-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: thelounge
  name: thelounge-data
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: scarif.lab.yaakov.online
    path: /volume1/ClusterData/microk8s/thelounge
