apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-yaakov.online
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@yaakov.online
    privateKeySecretRef:
      name: letsencrypt-yaakov.online
    dns01:
      providers:
        - name: cf-dns
          cloudflare:
            email: yaakov@ownmail.net
            apiKeySecretRef:
              name: cloudflare-api-key
              key: key
