apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: http.yaakov.online
  namespace: http-playground
spec:
  secretName: http.yaakov.online
  issuerRef:
    name: letsencrypt-yaakov.online
    kind: ClusterIssuer
  commonName: http.yaakov.online
  dnsNames:
    - http.yaakov.online
  acme:
    config:
      - dns01:
          provider: cf-dns
        domains:
        - http.yaakov.online
