---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: http-playground
  name: http-echo
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      service: http-echo
  template:
    metadata:
      labels:
        service: http-echo
    spec:
      containers:
      - name: http-echo
        image: solsson/http-echo
        ports:
        - containerPort: 80
          protocol: TCP
